### ISSUE TITLE
Dataset link is unavailable

### ISSUE THREAD

**Issue by Charlie17Li** [icloud-ecnu/Tetris#9]
Hi, when I follow the README, I found that executing the following command will fail: 

```
./data_download_1h.sh
```
I find that the dataset link is unavailable
![image](https://github.com/icloud-ecnu/Tetris/assets/32014420/867f845a-8804-4f46-b364-ccde0dc3e500)

**Comment by icloud-ecnu** [comment]
Hello Li,

Thanks for your interest in our project! We have checked the downloading permission of our dataset, and it has been changed to pubic. It's OK now. Please try again :)

**Comment by Charlie17Li** [comment]
@shenxiyue thx :)
